config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :consumer_accounts
  resources :banks
  resources :streets
  resources :consumers
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :street
  has_many :person_account
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: %i[ show edit update destroy ]

  # GET /consumers or /consumers.json
  def index
    @consumers = Consumer.all
  end

  # GET /consumers/1 or /consumers/1.json
  def show
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
    @streets = Street.all.map { |i| [i.name, i.id] }
  end

  # GET /consumers/1/edit
  def edit
  end

  # POST /consumers or /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    respond_to do |format|
      if @consumer.save
        format.html { redirect_to consumer_url(@consumer), notice: "Consumer was successfully created." }
        format.json { render :show, status: :created, location: @consumer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumers/1 or /consumers/1.json
  def update
    respond_to do |format|
      if @consumer.update(consumer_params)
        format.html { redirect_to consumer_url(@consumer), notice: "Consumer was successfully updated." }
        format.json { render :show, status: :ok, location: @consumer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumers/1 or /consumers/1.json
  def destroy
    @consumer.destroy

    respond_to do |format|
      format.html { redirect_to consumers_url, notice: "Consumer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consumer_params
      params.require(:consumer).permit(:full_name, :passport_number, :identity_code, :house, :house_section, :apartment, :street_id)
    end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_form.html.haml
= form_for @consumer do |f|
  - if @consumer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@consumer.errors.count, "error")} prohibited this consumer from being saved:"
      %ul
        - @consumer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :full_name
    = f.text_field :full_name
  .field
    = f.label :passport_number
    = f.text_field :passport_number
  .field
    = f.label :identity_code
    = f.text_field :identity_code
  .field
    = f.label :house
    = f.text_field :house
  .field
    = f.label :house_section
    = f.text_field :house_section
  .field
    = f.label :apartment
    = f.text_field :apartment
  .street
    = f.label :street_id, 'Вулиця'
    = f.select :street_id, @streets
  .actions
    = f.submit 'Save'

app/views/consumers/edit.html.haml
%h1 Editing consumer

= render 'form'

= link_to 'Show', @consumer
\|
= link_to 'Back', consumers_path

app/views/consumers/index.html.haml
%h1 Listing consumers

%table
  %thead
    %tr
      %th Full name
      %th Passport number
      %th Identity code
      %th Street
      %th House
      %th House section
      %th Apartment
      %th
      %th
      %th

  %tbody
    - @consumers.each do |consumer|
      %tr
        %td= consumer.full_name
        %td= consumer.passport_number
        %td= consumer.identity_code
        %td= consumer.street.name
        %td= consumer.house
        %td= consumer.house_section
        %td= consumer.apartment
        %td= link_to 'Show', consumer
        %td= link_to 'Edit', edit_consumer_path(consumer)
        %td= link_to 'Destroy', consumer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Consumer', new_consumer_path

app/views/consumers/new.html.haml
%h1 New consumer

= render 'form'

= link_to 'Back', consumers_path

app/views/consumers/show.html.haml
%p#notice= notice

%p
  %b Full name:
  = @consumer.full_name
%p
  %b Passport number:
  = @consumer.passport_number
%p
  %b Identity code:
  = @consumer.identity_code
%p
  %b Street: 
  = @consumer.street.name
%p
  %b House:
  = @consumer.house
%p
  %b House section:
  = @consumer.house_section
%p
  %b Apartment:
  = @consumer.apartment

= link_to 'Edit', edit_consumer_path(@consumer)
\|
= link_to 'Back', consumers_path