config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :consumer_accounts
  resources :banks
  resources :streets
  resources :consumers
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bank.rb
class Bank < ApplicationRecord
  has_many :person_account
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: %i[ show edit update destroy ]

  # GET /banks or /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1 or /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks or /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully created." }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully updated." }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_params
      params.require(:bank).permit(:name, :edrpou, :mfo)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.haml
= form_for @bank do |f|
  - if @bank.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bank.errors.count, "error")} prohibited this bank from being saved:"
      %ul
        - @bank.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :edrpou
    = f.text_field :edrpou
  .field
    = f.label :mfo
    = f.text_field :mfo
  .actions
    = f.submit 'Save'

app/views/banks/edit.html.haml
%h1 Editing bank

= render 'form'

= link_to 'Show', @bank
\|
= link_to 'Back', banks_path

app/views/banks/index.html.haml
%h1 Listing banks

%table
  %thead
    %tr
      %th Name
      %th Edrpou
      %th Mfo
      %th
      %th
      %th

  %tbody
    - @banks.each do |bank|
      %tr
        %td= bank.name
        %td= bank.edrpou
        %td= bank.mfo
        %td= link_to 'Show', bank
        %td= link_to 'Edit', edit_bank_path(bank)
        %td= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Bank', new_bank_path

app/views/banks/new.html.haml
%h1 New bank

= render 'form'

= link_to 'Back', banks_path

app/views/banks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bank.name
%p
  %b Edrpou:
  = @bank.edrpou
%p
  %b Mfo:
  = @bank.mfo

= link_to 'Edit', edit_bank_path(@bank)
\|
= link_to 'Back', banks_path