config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :consumer_accounts
  resources :banks
  resources :streets
  resources :consumers
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:date, :paid, :report_number, :description, :sum, :code_kfk, :code_kek)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for @payment do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @payment.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :date
    = f.date_field :date
  .field
    = f.label :paid
    = f.check_box :paid
  .field
    = f.label :report_number
    = f.text_field :report_number
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :sum
    = f.text_field :sum
  .field
    = f.label :code_kfk
    = f.text_field :code_kfk
  .field
    = f.label :code_kek
    = f.text_field :code_kek
  .actions
    = f.submit 'Save'

app/views/payments/edit.html.haml
%h1 Editing payment

= render 'form'

= link_to 'Show', @payment
\|
= link_to 'Back', payments_path

app/views/payments/index.html.haml
%h1 Listing payments

%table
  %thead
    %tr
      %th Date
      %th Paid
      %th Report number
      %th Description
      %th Sum
      %th Code kfk
      %th Code kek
      %th
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.date
        %td= payment.paid
        %td= payment.report_number
        %td= payment.description
        %td= payment.sum
        %td= payment.code_kfk
        %td= payment.code_kek
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Payment', new_payment_path

app/views/payments/new.html.haml
%h1 New payment

= render 'form'

= link_to 'Back', payments_path

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @payment.date
%p
  %b Paid:
  = @payment.paid
%p
  %b Report number:
  = @payment.report_number
%p
  %b Description:
  = @payment.description
%p
  %b Sum:
  = @payment.sum
%p
  %b Code kfk:
  = @payment.code_kfk
%p
  %b Code kek:
  = @payment.code_kek

= link_to 'Edit', edit_payment_path(@payment)
\|
= link_to 'Back', payments_path